[package]
name = "noir_data_deletion_request"
type = "bin"
authors = ["DataGuardiansZK"] 
compiler_version = ">=0.20.0" # Adjust if necessary, e.g., "0.27.0"

[dependencies]
# For Pedersen hash
noir_stdlib = { tag = "v0.6.0", git = "https://github.com/noir-lang/noir-libs/" , directory="stdlib"}
